CC = gcc
CFLAGS = -Wall
LDFLAGS =
TARGET = FA_SIMECK32 FA_SIMECK48 FA_SIMECK64

all: $(TARGET)

FA_SIMECK32: FA_SIMECK32.c
	$(CC) $(CFLAGS) -o FA_SIMECK32 FA_SIMECK32.c $(LDFLAGS)

FA_SIMECK48: FA_SIMECK48.c
	$(CC) $(CFLAGS) -o FA_SIMECK48 FA_SIMECK48.c $(LDFLAGS)

FA_SIMECK64: FA_SIMECK64.c
	$(CC) $(CFLAGS) -o FA_SIMECK64 FA_SIMECK64.c $(LDFLAGS)

clean:
	rm -f $(TARGET) *~